//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Px4
{
    [Serializable]
    public class TentacleConfigMsg : Message
    {
        public const string k_RosMessageName = "px4_msgs/TentacleConfig";
        public override string RosMessageName => k_RosMessageName;

        public double qal;
        public double qar;
        public double qll;
        public double qlr;

        public TentacleConfigMsg()
        {
            this.qal = 0.0;
            this.qar = 0.0;
            this.qll = 0.0;
            this.qlr = 0.0;
        }

        public TentacleConfigMsg(double qal, double qar, double qll, double qlr)
        {
            this.qal = qal;
            this.qar = qar;
            this.qll = qll;
            this.qlr = qlr;
        }

        public static TentacleConfigMsg Deserialize(MessageDeserializer deserializer) => new TentacleConfigMsg(deserializer);

        private TentacleConfigMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.qal);
            deserializer.Read(out this.qar);
            deserializer.Read(out this.qll);
            deserializer.Read(out this.qlr);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.qal);
            serializer.Write(this.qar);
            serializer.Write(this.qll);
            serializer.Write(this.qlr);
        }

        public override string ToString()
        {
            return "TentacleConfigMsg: " +
            "\nqal: " + qal.ToString() +
            "\nqar: " + qar.ToString() +
            "\nqll: " + qll.ToString() +
            "\nqlr: " + qlr.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
