//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Px4
{
    [Serializable]
    public class UAMCommandMsg : Message
    {
        public const string k_RosMessageName = "px4_msgs/UAMCommand";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.TwistMsg uav_vel;
        public Geometry.PoseMsg uav_pose;
        public short uav_mode;
        public short robot_mode;
        public short robot_bypass_planner;
        public Geometry.TwistMsg robot_actions;

        public UAMCommandMsg()
        {
            this.uav_vel = new Geometry.TwistMsg();
            this.uav_pose = new Geometry.PoseMsg();
            this.uav_mode = 0;
            this.robot_mode = 0;
            this.robot_bypass_planner = 0;
            this.robot_actions = new Geometry.TwistMsg();
        }

        public UAMCommandMsg(Geometry.TwistMsg uav_vel, Geometry.PoseMsg uav_pose, short uav_mode, short robot_mode, short robot_bypass_planner, Geometry.TwistMsg robot_actions)
        {
            this.uav_vel = uav_vel;
            this.uav_pose = uav_pose;
            this.uav_mode = uav_mode;
            this.robot_mode = robot_mode;
            this.robot_bypass_planner = robot_bypass_planner;
            this.robot_actions = robot_actions;
        }

        public static UAMCommandMsg Deserialize(MessageDeserializer deserializer) => new UAMCommandMsg(deserializer);

        private UAMCommandMsg(MessageDeserializer deserializer)
        {
            this.uav_vel = Geometry.TwistMsg.Deserialize(deserializer);
            this.uav_pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.uav_mode);
            deserializer.Read(out this.robot_mode);
            deserializer.Read(out this.robot_bypass_planner);
            this.robot_actions = Geometry.TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.uav_vel);
            serializer.Write(this.uav_pose);
            serializer.Write(this.uav_mode);
            serializer.Write(this.robot_mode);
            serializer.Write(this.robot_bypass_planner);
            serializer.Write(this.robot_actions);
        }

        public override string ToString()
        {
            return "UAMCommandMsg: " +
            "\nuav_vel: " + uav_vel.ToString() +
            "\nuav_pose: " + uav_pose.ToString() +
            "\nuav_mode: " + uav_mode.ToString() +
            "\nrobot_mode: " + robot_mode.ToString() +
            "\nrobot_bypass_planner: " + robot_bypass_planner.ToString() +
            "\nrobot_actions: " + robot_actions.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
